### ISSUE TITLE
FF133 incompatibility

### ISSUE THREAD

**Issue by I-Knight-I** [WesleyBranton/Remove-Firefox-Megabar#14]
Firefox 133.0 has broken this for me. 

When clicked on, the address bar is anchored to the top left of my screen and the megabar is still there:

![image](https://github.com/user-attachments/assets/9cf02515-b1ed-4add-bc47-5641fb67f488)

**Comment by ssokolow** [comment]
As a quick temporary hack to get something less noticeable, I replaced

```css
    #urlbar[breakout][breakout-extend] {
        top: calc((var(--urlbar-container-height) - var(--urlbar-height)) / 2) !important;
        left: 0 !important;
        width: 100% !important;
    }
```

with

```css
    #urlbar[breakout][breakout-extend] {
        margin: 4px;
    }
```
